// flow-typed signature: fe5978011e3dd3565eea63359a9e0ba4
// flow-typed version: <<STUB>>/firebase-tools_v^6.1.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-tools/lib/accountExporter' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/accountImporter' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/api' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/auth' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/bin/firebase' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/checkDupHostingKeys' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/checkFirebaseSDKVersion' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/checkValidTargetFilters' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/command' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/auth-export' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/auth-import' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/database-get' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/database-profile' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/database-push' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/database-remove' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/database-set' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/database-update' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/deploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/experimental-functions-shell' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/firestore-delete' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/firestore-indexes-list' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/functions-config-clone' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/functions-config-get' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/functions-config-legacy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/functions-config-set' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/functions-config-unset' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/functions-delete' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/functions-log' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/functions-shell' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/help' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/hosting-disable' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/init' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/kits-install' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/kits-uninstall' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/list' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/login-ci' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/login' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/logout' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/open' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/serve' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/setup-emulators-database' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/setup-emulators-firestore' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/setup-web' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/target-apply' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/target-clear' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/target-remove' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/target' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/tools-migrate' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/commands/use' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/config' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/configstore' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/database/remove' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/database/removeRemote' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/database/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/database/prepare' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/database/release' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/firestore/deploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/firestore/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/firestore/prepare' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/firestore/release' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/functions/deploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/functions/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/functions/prepare' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/functions/release' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/convertConfig' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/deploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/hashcache' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/prepare' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/release' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/hosting/uploader' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/lifecycleHooks' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/storage/deploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/storage/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/storage/prepare' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploy/storage/release' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/deploymentTool' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/detectProjectRoot' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/emulator/constants' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/emulator/download' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/ensureApiEnabled' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/ensureDefaultCredentials' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/error' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/errorOut' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/extractTriggers' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/fetchMOTD' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/fetchWebSetup' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/filterTargets' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/firebaseApi' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/firestore/delete' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/firestore/encodeFirestoreValue' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/firestore/indexes' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/fsAsync' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/fsutils' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/functionsConfig' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/functionsConfigClone' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/functionsDelete' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/functionsDeployHelper' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/functionsEmulator' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/functionsShellCommandAction' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/cloudfunctions' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/cloudlogging' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/firestore' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/rules' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/runtimeconfig' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/gcp/storage' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/getInstanceId' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/getProjectId' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/getProjectNumber' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/handlePreviewToggles' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/hosting/functionsProxy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/hosting/implicitInit' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/hosting/initMiddleware' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/hosting/normalizedHostingConfigs' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/identifierToProjectId' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/database' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/firestore' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/functions/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/functions/javascript' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/functions/npm-dependencies' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/functions/typescript' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/hosting' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/project' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/features/storage' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/init/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/kits/deploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/kits/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/kits/pollKits' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/kits/prepareKitsConfig' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/kits/prepareKitsUpload' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/listFiles' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/loadCJSON' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/localFunction' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/logError' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/logger' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/parseBoltRules' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/parseTriggers' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/pollOperations' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/prepareFirebaseRules' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/prepareFunctionsUpload' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/prepareUpload' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/previews' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/profiler' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/profileReport' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/prompt' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/queue' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/rc' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/requireAccess' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/requireAuth' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/requireConfig' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/requireInstance' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/requirePermissions' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/resolveProjectPath' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/responseToError' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/rtdb' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/RulesDeploy' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/scopes' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/serve/database' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/serve/firestore' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/serve/functions' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/serve/hosting' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/serve/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/serve/javaEmulators' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/accountExporter.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/accountImporter.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/command.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/config.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/database/remove.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/database/removeRemote.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/extractTriggers.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/fsAsync.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/fsutils.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/functionsConfig.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/functionsDeployHelper.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/helpers/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/helpers/mocha-bootstrap' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/identifierToProjectId.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/listFiles.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/localFunction.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/profilerReport.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/queue.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/rc.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/test/utils.spec' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/track' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/triggerParser' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/utils' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/validateJsonRules' {
  declare module.exports: any;
}

declare module 'firebase-tools/lib/validator' {
  declare module.exports: any;
}

declare module 'firebase-tools/templates/hosting/init' {
  declare module.exports: any;
}

declare module 'firebase-tools/templates/init/functions/javascript/index' {
  declare module.exports: any;
}

declare module 'firebase-tools/templates/setup/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-tools/lib/accountExporter.js' {
  declare module.exports: $Exports<'firebase-tools/lib/accountExporter'>;
}
declare module 'firebase-tools/lib/accountImporter.js' {
  declare module.exports: $Exports<'firebase-tools/lib/accountImporter'>;
}
declare module 'firebase-tools/lib/api.js' {
  declare module.exports: $Exports<'firebase-tools/lib/api'>;
}
declare module 'firebase-tools/lib/auth.js' {
  declare module.exports: $Exports<'firebase-tools/lib/auth'>;
}
declare module 'firebase-tools/lib/bin/firebase.js' {
  declare module.exports: $Exports<'firebase-tools/lib/bin/firebase'>;
}
declare module 'firebase-tools/lib/checkDupHostingKeys.js' {
  declare module.exports: $Exports<'firebase-tools/lib/checkDupHostingKeys'>;
}
declare module 'firebase-tools/lib/checkFirebaseSDKVersion.js' {
  declare module.exports: $Exports<'firebase-tools/lib/checkFirebaseSDKVersion'>;
}
declare module 'firebase-tools/lib/checkValidTargetFilters.js' {
  declare module.exports: $Exports<'firebase-tools/lib/checkValidTargetFilters'>;
}
declare module 'firebase-tools/lib/command.js' {
  declare module.exports: $Exports<'firebase-tools/lib/command'>;
}
declare module 'firebase-tools/lib/commands/auth-export.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/auth-export'>;
}
declare module 'firebase-tools/lib/commands/auth-import.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/auth-import'>;
}
declare module 'firebase-tools/lib/commands/database-get.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/database-get'>;
}
declare module 'firebase-tools/lib/commands/database-profile.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/database-profile'>;
}
declare module 'firebase-tools/lib/commands/database-push.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/database-push'>;
}
declare module 'firebase-tools/lib/commands/database-remove.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/database-remove'>;
}
declare module 'firebase-tools/lib/commands/database-set.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/database-set'>;
}
declare module 'firebase-tools/lib/commands/database-update.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/database-update'>;
}
declare module 'firebase-tools/lib/commands/deploy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/deploy'>;
}
declare module 'firebase-tools/lib/commands/experimental-functions-shell.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/experimental-functions-shell'>;
}
declare module 'firebase-tools/lib/commands/firestore-delete.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/firestore-delete'>;
}
declare module 'firebase-tools/lib/commands/firestore-indexes-list.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/firestore-indexes-list'>;
}
declare module 'firebase-tools/lib/commands/functions-config-clone.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/functions-config-clone'>;
}
declare module 'firebase-tools/lib/commands/functions-config-get.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/functions-config-get'>;
}
declare module 'firebase-tools/lib/commands/functions-config-legacy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/functions-config-legacy'>;
}
declare module 'firebase-tools/lib/commands/functions-config-set.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/functions-config-set'>;
}
declare module 'firebase-tools/lib/commands/functions-config-unset.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/functions-config-unset'>;
}
declare module 'firebase-tools/lib/commands/functions-delete.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/functions-delete'>;
}
declare module 'firebase-tools/lib/commands/functions-log.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/functions-log'>;
}
declare module 'firebase-tools/lib/commands/functions-shell.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/functions-shell'>;
}
declare module 'firebase-tools/lib/commands/help.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/help'>;
}
declare module 'firebase-tools/lib/commands/hosting-disable.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/hosting-disable'>;
}
declare module 'firebase-tools/lib/commands/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/index'>;
}
declare module 'firebase-tools/lib/commands/init.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/init'>;
}
declare module 'firebase-tools/lib/commands/kits-install.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/kits-install'>;
}
declare module 'firebase-tools/lib/commands/kits-uninstall.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/kits-uninstall'>;
}
declare module 'firebase-tools/lib/commands/list.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/list'>;
}
declare module 'firebase-tools/lib/commands/login-ci.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/login-ci'>;
}
declare module 'firebase-tools/lib/commands/login.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/login'>;
}
declare module 'firebase-tools/lib/commands/logout.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/logout'>;
}
declare module 'firebase-tools/lib/commands/open.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/open'>;
}
declare module 'firebase-tools/lib/commands/serve.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/serve'>;
}
declare module 'firebase-tools/lib/commands/setup-emulators-database.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/setup-emulators-database'>;
}
declare module 'firebase-tools/lib/commands/setup-emulators-firestore.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/setup-emulators-firestore'>;
}
declare module 'firebase-tools/lib/commands/setup-web.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/setup-web'>;
}
declare module 'firebase-tools/lib/commands/target-apply.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/target-apply'>;
}
declare module 'firebase-tools/lib/commands/target-clear.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/target-clear'>;
}
declare module 'firebase-tools/lib/commands/target-remove.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/target-remove'>;
}
declare module 'firebase-tools/lib/commands/target.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/target'>;
}
declare module 'firebase-tools/lib/commands/tools-migrate.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/tools-migrate'>;
}
declare module 'firebase-tools/lib/commands/use.js' {
  declare module.exports: $Exports<'firebase-tools/lib/commands/use'>;
}
declare module 'firebase-tools/lib/config.js' {
  declare module.exports: $Exports<'firebase-tools/lib/config'>;
}
declare module 'firebase-tools/lib/configstore.js' {
  declare module.exports: $Exports<'firebase-tools/lib/configstore'>;
}
declare module 'firebase-tools/lib/database/remove.js' {
  declare module.exports: $Exports<'firebase-tools/lib/database/remove'>;
}
declare module 'firebase-tools/lib/database/removeRemote.js' {
  declare module.exports: $Exports<'firebase-tools/lib/database/removeRemote'>;
}
declare module 'firebase-tools/lib/deploy/database/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/database/index'>;
}
declare module 'firebase-tools/lib/deploy/database/prepare.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/database/prepare'>;
}
declare module 'firebase-tools/lib/deploy/database/release.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/database/release'>;
}
declare module 'firebase-tools/lib/deploy/firestore/deploy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/firestore/deploy'>;
}
declare module 'firebase-tools/lib/deploy/firestore/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/firestore/index'>;
}
declare module 'firebase-tools/lib/deploy/firestore/prepare.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/firestore/prepare'>;
}
declare module 'firebase-tools/lib/deploy/firestore/release.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/firestore/release'>;
}
declare module 'firebase-tools/lib/deploy/functions/deploy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/functions/deploy'>;
}
declare module 'firebase-tools/lib/deploy/functions/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/functions/index'>;
}
declare module 'firebase-tools/lib/deploy/functions/prepare.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/functions/prepare'>;
}
declare module 'firebase-tools/lib/deploy/functions/release.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/functions/release'>;
}
declare module 'firebase-tools/lib/deploy/hosting/convertConfig.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/convertConfig'>;
}
declare module 'firebase-tools/lib/deploy/hosting/deploy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/deploy'>;
}
declare module 'firebase-tools/lib/deploy/hosting/hashcache.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/hashcache'>;
}
declare module 'firebase-tools/lib/deploy/hosting/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/index'>;
}
declare module 'firebase-tools/lib/deploy/hosting/prepare.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/prepare'>;
}
declare module 'firebase-tools/lib/deploy/hosting/release.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/release'>;
}
declare module 'firebase-tools/lib/deploy/hosting/uploader.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/hosting/uploader'>;
}
declare module 'firebase-tools/lib/deploy/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/index'>;
}
declare module 'firebase-tools/lib/deploy/lifecycleHooks.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/lifecycleHooks'>;
}
declare module 'firebase-tools/lib/deploy/storage/deploy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/storage/deploy'>;
}
declare module 'firebase-tools/lib/deploy/storage/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/storage/index'>;
}
declare module 'firebase-tools/lib/deploy/storage/prepare.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/storage/prepare'>;
}
declare module 'firebase-tools/lib/deploy/storage/release.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploy/storage/release'>;
}
declare module 'firebase-tools/lib/deploymentTool.js' {
  declare module.exports: $Exports<'firebase-tools/lib/deploymentTool'>;
}
declare module 'firebase-tools/lib/detectProjectRoot.js' {
  declare module.exports: $Exports<'firebase-tools/lib/detectProjectRoot'>;
}
declare module 'firebase-tools/lib/emulator/constants.js' {
  declare module.exports: $Exports<'firebase-tools/lib/emulator/constants'>;
}
declare module 'firebase-tools/lib/emulator/download.js' {
  declare module.exports: $Exports<'firebase-tools/lib/emulator/download'>;
}
declare module 'firebase-tools/lib/ensureApiEnabled.js' {
  declare module.exports: $Exports<'firebase-tools/lib/ensureApiEnabled'>;
}
declare module 'firebase-tools/lib/ensureDefaultCredentials.js' {
  declare module.exports: $Exports<'firebase-tools/lib/ensureDefaultCredentials'>;
}
declare module 'firebase-tools/lib/error.js' {
  declare module.exports: $Exports<'firebase-tools/lib/error'>;
}
declare module 'firebase-tools/lib/errorOut.js' {
  declare module.exports: $Exports<'firebase-tools/lib/errorOut'>;
}
declare module 'firebase-tools/lib/extractTriggers.js' {
  declare module.exports: $Exports<'firebase-tools/lib/extractTriggers'>;
}
declare module 'firebase-tools/lib/fetchMOTD.js' {
  declare module.exports: $Exports<'firebase-tools/lib/fetchMOTD'>;
}
declare module 'firebase-tools/lib/fetchWebSetup.js' {
  declare module.exports: $Exports<'firebase-tools/lib/fetchWebSetup'>;
}
declare module 'firebase-tools/lib/filterTargets.js' {
  declare module.exports: $Exports<'firebase-tools/lib/filterTargets'>;
}
declare module 'firebase-tools/lib/firebaseApi.js' {
  declare module.exports: $Exports<'firebase-tools/lib/firebaseApi'>;
}
declare module 'firebase-tools/lib/firestore/delete.js' {
  declare module.exports: $Exports<'firebase-tools/lib/firestore/delete'>;
}
declare module 'firebase-tools/lib/firestore/encodeFirestoreValue.js' {
  declare module.exports: $Exports<'firebase-tools/lib/firestore/encodeFirestoreValue'>;
}
declare module 'firebase-tools/lib/firestore/indexes.js' {
  declare module.exports: $Exports<'firebase-tools/lib/firestore/indexes'>;
}
declare module 'firebase-tools/lib/fsAsync.js' {
  declare module.exports: $Exports<'firebase-tools/lib/fsAsync'>;
}
declare module 'firebase-tools/lib/fsutils.js' {
  declare module.exports: $Exports<'firebase-tools/lib/fsutils'>;
}
declare module 'firebase-tools/lib/functionsConfig.js' {
  declare module.exports: $Exports<'firebase-tools/lib/functionsConfig'>;
}
declare module 'firebase-tools/lib/functionsConfigClone.js' {
  declare module.exports: $Exports<'firebase-tools/lib/functionsConfigClone'>;
}
declare module 'firebase-tools/lib/functionsDelete.js' {
  declare module.exports: $Exports<'firebase-tools/lib/functionsDelete'>;
}
declare module 'firebase-tools/lib/functionsDeployHelper.js' {
  declare module.exports: $Exports<'firebase-tools/lib/functionsDeployHelper'>;
}
declare module 'firebase-tools/lib/functionsEmulator.js' {
  declare module.exports: $Exports<'firebase-tools/lib/functionsEmulator'>;
}
declare module 'firebase-tools/lib/functionsShellCommandAction.js' {
  declare module.exports: $Exports<'firebase-tools/lib/functionsShellCommandAction'>;
}
declare module 'firebase-tools/lib/gcp/cloudfunctions.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/cloudfunctions'>;
}
declare module 'firebase-tools/lib/gcp/cloudlogging.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/cloudlogging'>;
}
declare module 'firebase-tools/lib/gcp/firestore.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/firestore'>;
}
declare module 'firebase-tools/lib/gcp/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/index'>;
}
declare module 'firebase-tools/lib/gcp/rules.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/rules'>;
}
declare module 'firebase-tools/lib/gcp/runtimeconfig.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/runtimeconfig'>;
}
declare module 'firebase-tools/lib/gcp/storage.js' {
  declare module.exports: $Exports<'firebase-tools/lib/gcp/storage'>;
}
declare module 'firebase-tools/lib/getInstanceId.js' {
  declare module.exports: $Exports<'firebase-tools/lib/getInstanceId'>;
}
declare module 'firebase-tools/lib/getProjectId.js' {
  declare module.exports: $Exports<'firebase-tools/lib/getProjectId'>;
}
declare module 'firebase-tools/lib/getProjectNumber.js' {
  declare module.exports: $Exports<'firebase-tools/lib/getProjectNumber'>;
}
declare module 'firebase-tools/lib/handlePreviewToggles.js' {
  declare module.exports: $Exports<'firebase-tools/lib/handlePreviewToggles'>;
}
declare module 'firebase-tools/lib/hosting/functionsProxy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/hosting/functionsProxy'>;
}
declare module 'firebase-tools/lib/hosting/implicitInit.js' {
  declare module.exports: $Exports<'firebase-tools/lib/hosting/implicitInit'>;
}
declare module 'firebase-tools/lib/hosting/initMiddleware.js' {
  declare module.exports: $Exports<'firebase-tools/lib/hosting/initMiddleware'>;
}
declare module 'firebase-tools/lib/hosting/normalizedHostingConfigs.js' {
  declare module.exports: $Exports<'firebase-tools/lib/hosting/normalizedHostingConfigs'>;
}
declare module 'firebase-tools/lib/identifierToProjectId.js' {
  declare module.exports: $Exports<'firebase-tools/lib/identifierToProjectId'>;
}
declare module 'firebase-tools/lib/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/index'>;
}
declare module 'firebase-tools/lib/init/features/database.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/database'>;
}
declare module 'firebase-tools/lib/init/features/firestore.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/firestore'>;
}
declare module 'firebase-tools/lib/init/features/functions/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/functions/index'>;
}
declare module 'firebase-tools/lib/init/features/functions/javascript.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/functions/javascript'>;
}
declare module 'firebase-tools/lib/init/features/functions/npm-dependencies.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/functions/npm-dependencies'>;
}
declare module 'firebase-tools/lib/init/features/functions/typescript.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/functions/typescript'>;
}
declare module 'firebase-tools/lib/init/features/hosting.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/hosting'>;
}
declare module 'firebase-tools/lib/init/features/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/index'>;
}
declare module 'firebase-tools/lib/init/features/project.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/project'>;
}
declare module 'firebase-tools/lib/init/features/storage.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/features/storage'>;
}
declare module 'firebase-tools/lib/init/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/init/index'>;
}
declare module 'firebase-tools/lib/kits/deploy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/kits/deploy'>;
}
declare module 'firebase-tools/lib/kits/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/kits/index'>;
}
declare module 'firebase-tools/lib/kits/pollKits.js' {
  declare module.exports: $Exports<'firebase-tools/lib/kits/pollKits'>;
}
declare module 'firebase-tools/lib/kits/prepareKitsConfig.js' {
  declare module.exports: $Exports<'firebase-tools/lib/kits/prepareKitsConfig'>;
}
declare module 'firebase-tools/lib/kits/prepareKitsUpload.js' {
  declare module.exports: $Exports<'firebase-tools/lib/kits/prepareKitsUpload'>;
}
declare module 'firebase-tools/lib/listFiles.js' {
  declare module.exports: $Exports<'firebase-tools/lib/listFiles'>;
}
declare module 'firebase-tools/lib/loadCJSON.js' {
  declare module.exports: $Exports<'firebase-tools/lib/loadCJSON'>;
}
declare module 'firebase-tools/lib/localFunction.js' {
  declare module.exports: $Exports<'firebase-tools/lib/localFunction'>;
}
declare module 'firebase-tools/lib/logError.js' {
  declare module.exports: $Exports<'firebase-tools/lib/logError'>;
}
declare module 'firebase-tools/lib/logger.js' {
  declare module.exports: $Exports<'firebase-tools/lib/logger'>;
}
declare module 'firebase-tools/lib/parseBoltRules.js' {
  declare module.exports: $Exports<'firebase-tools/lib/parseBoltRules'>;
}
declare module 'firebase-tools/lib/parseTriggers.js' {
  declare module.exports: $Exports<'firebase-tools/lib/parseTriggers'>;
}
declare module 'firebase-tools/lib/pollOperations.js' {
  declare module.exports: $Exports<'firebase-tools/lib/pollOperations'>;
}
declare module 'firebase-tools/lib/prepareFirebaseRules.js' {
  declare module.exports: $Exports<'firebase-tools/lib/prepareFirebaseRules'>;
}
declare module 'firebase-tools/lib/prepareFunctionsUpload.js' {
  declare module.exports: $Exports<'firebase-tools/lib/prepareFunctionsUpload'>;
}
declare module 'firebase-tools/lib/prepareUpload.js' {
  declare module.exports: $Exports<'firebase-tools/lib/prepareUpload'>;
}
declare module 'firebase-tools/lib/previews.js' {
  declare module.exports: $Exports<'firebase-tools/lib/previews'>;
}
declare module 'firebase-tools/lib/profiler.js' {
  declare module.exports: $Exports<'firebase-tools/lib/profiler'>;
}
declare module 'firebase-tools/lib/profileReport.js' {
  declare module.exports: $Exports<'firebase-tools/lib/profileReport'>;
}
declare module 'firebase-tools/lib/prompt.js' {
  declare module.exports: $Exports<'firebase-tools/lib/prompt'>;
}
declare module 'firebase-tools/lib/queue.js' {
  declare module.exports: $Exports<'firebase-tools/lib/queue'>;
}
declare module 'firebase-tools/lib/rc.js' {
  declare module.exports: $Exports<'firebase-tools/lib/rc'>;
}
declare module 'firebase-tools/lib/requireAccess.js' {
  declare module.exports: $Exports<'firebase-tools/lib/requireAccess'>;
}
declare module 'firebase-tools/lib/requireAuth.js' {
  declare module.exports: $Exports<'firebase-tools/lib/requireAuth'>;
}
declare module 'firebase-tools/lib/requireConfig.js' {
  declare module.exports: $Exports<'firebase-tools/lib/requireConfig'>;
}
declare module 'firebase-tools/lib/requireInstance.js' {
  declare module.exports: $Exports<'firebase-tools/lib/requireInstance'>;
}
declare module 'firebase-tools/lib/requirePermissions.js' {
  declare module.exports: $Exports<'firebase-tools/lib/requirePermissions'>;
}
declare module 'firebase-tools/lib/resolveProjectPath.js' {
  declare module.exports: $Exports<'firebase-tools/lib/resolveProjectPath'>;
}
declare module 'firebase-tools/lib/responseToError.js' {
  declare module.exports: $Exports<'firebase-tools/lib/responseToError'>;
}
declare module 'firebase-tools/lib/rtdb.js' {
  declare module.exports: $Exports<'firebase-tools/lib/rtdb'>;
}
declare module 'firebase-tools/lib/RulesDeploy.js' {
  declare module.exports: $Exports<'firebase-tools/lib/RulesDeploy'>;
}
declare module 'firebase-tools/lib/scopes.js' {
  declare module.exports: $Exports<'firebase-tools/lib/scopes'>;
}
declare module 'firebase-tools/lib/serve/database.js' {
  declare module.exports: $Exports<'firebase-tools/lib/serve/database'>;
}
declare module 'firebase-tools/lib/serve/firestore.js' {
  declare module.exports: $Exports<'firebase-tools/lib/serve/firestore'>;
}
declare module 'firebase-tools/lib/serve/functions.js' {
  declare module.exports: $Exports<'firebase-tools/lib/serve/functions'>;
}
declare module 'firebase-tools/lib/serve/hosting.js' {
  declare module.exports: $Exports<'firebase-tools/lib/serve/hosting'>;
}
declare module 'firebase-tools/lib/serve/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/serve/index'>;
}
declare module 'firebase-tools/lib/serve/javaEmulators.js' {
  declare module.exports: $Exports<'firebase-tools/lib/serve/javaEmulators'>;
}
declare module 'firebase-tools/lib/test/accountExporter.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/accountExporter.spec'>;
}
declare module 'firebase-tools/lib/test/accountImporter.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/accountImporter.spec'>;
}
declare module 'firebase-tools/lib/test/command.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/command.spec'>;
}
declare module 'firebase-tools/lib/test/config.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/config.spec'>;
}
declare module 'firebase-tools/lib/test/database/remove.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/database/remove.spec'>;
}
declare module 'firebase-tools/lib/test/database/removeRemote.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/database/removeRemote.spec'>;
}
declare module 'firebase-tools/lib/test/extractTriggers.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/extractTriggers.spec'>;
}
declare module 'firebase-tools/lib/test/fsAsync.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/fsAsync.spec'>;
}
declare module 'firebase-tools/lib/test/fsutils.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/fsutils.spec'>;
}
declare module 'firebase-tools/lib/test/functionsConfig.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/functionsConfig.spec'>;
}
declare module 'firebase-tools/lib/test/functionsDeployHelper.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/functionsDeployHelper.spec'>;
}
declare module 'firebase-tools/lib/test/helpers/index.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/helpers/index'>;
}
declare module 'firebase-tools/lib/test/helpers/mocha-bootstrap.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/helpers/mocha-bootstrap'>;
}
declare module 'firebase-tools/lib/test/identifierToProjectId.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/identifierToProjectId.spec'>;
}
declare module 'firebase-tools/lib/test/listFiles.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/listFiles.spec'>;
}
declare module 'firebase-tools/lib/test/localFunction.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/localFunction.spec'>;
}
declare module 'firebase-tools/lib/test/profilerReport.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/profilerReport.spec'>;
}
declare module 'firebase-tools/lib/test/queue.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/queue.spec'>;
}
declare module 'firebase-tools/lib/test/rc.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/rc.spec'>;
}
declare module 'firebase-tools/lib/test/utils.spec.js' {
  declare module.exports: $Exports<'firebase-tools/lib/test/utils.spec'>;
}
declare module 'firebase-tools/lib/track.js' {
  declare module.exports: $Exports<'firebase-tools/lib/track'>;
}
declare module 'firebase-tools/lib/triggerParser.js' {
  declare module.exports: $Exports<'firebase-tools/lib/triggerParser'>;
}
declare module 'firebase-tools/lib/utils.js' {
  declare module.exports: $Exports<'firebase-tools/lib/utils'>;
}
declare module 'firebase-tools/lib/validateJsonRules.js' {
  declare module.exports: $Exports<'firebase-tools/lib/validateJsonRules'>;
}
declare module 'firebase-tools/lib/validator.js' {
  declare module.exports: $Exports<'firebase-tools/lib/validator'>;
}
declare module 'firebase-tools/templates/hosting/init.js' {
  declare module.exports: $Exports<'firebase-tools/templates/hosting/init'>;
}
declare module 'firebase-tools/templates/init/functions/javascript/index.js' {
  declare module.exports: $Exports<'firebase-tools/templates/init/functions/javascript/index'>;
}
declare module 'firebase-tools/templates/setup/web.js' {
  declare module.exports: $Exports<'firebase-tools/templates/setup/web'>;
}
