// flow-typed signature: 862e6ec64b19ed72f960f5e886000051
// flow-typed version: <<STUB>>/next-redux-wrapper_v^2.0.0-beta.6/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-redux-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-redux-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-redux-wrapper/components/layout' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/components/reducer' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/components/store' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/lib/index' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/lib/index.spec' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/_app' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/_error' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/index' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/other' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/out/_next/static/commons/main-db57ccbd588a2d307194' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/out/_next/static/commons/main' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/out/_next/static/commons/manifest' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/src/index' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/src/index.spec' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-redux-wrapper/components/layout.js' {
  declare module.exports: $Exports<'next-redux-wrapper/components/layout'>;
}
declare module 'next-redux-wrapper/components/reducer.js' {
  declare module.exports: $Exports<'next-redux-wrapper/components/reducer'>;
}
declare module 'next-redux-wrapper/components/store.js' {
  declare module.exports: $Exports<'next-redux-wrapper/components/store'>;
}
declare module 'next-redux-wrapper/lib/index.js' {
  declare module.exports: $Exports<'next-redux-wrapper/lib/index'>;
}
declare module 'next-redux-wrapper/lib/index.spec.js' {
  declare module.exports: $Exports<'next-redux-wrapper/lib/index.spec'>;
}
declare module 'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/_app.js' {
  declare module.exports: $Exports<'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/_app'>;
}
declare module 'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/_error.js' {
  declare module.exports: $Exports<'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/_error'>;
}
declare module 'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/index.js' {
  declare module.exports: $Exports<'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/index'>;
}
declare module 'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/other.js' {
  declare module.exports: $Exports<'next-redux-wrapper/out/_next/6c736efa-8719-41d2-9ff1-4c33bb2300e9/page/other'>;
}
declare module 'next-redux-wrapper/out/_next/static/commons/main-db57ccbd588a2d307194.js' {
  declare module.exports: $Exports<'next-redux-wrapper/out/_next/static/commons/main-db57ccbd588a2d307194'>;
}
declare module 'next-redux-wrapper/out/_next/static/commons/main.js' {
  declare module.exports: $Exports<'next-redux-wrapper/out/_next/static/commons/main'>;
}
declare module 'next-redux-wrapper/out/_next/static/commons/manifest.js' {
  declare module.exports: $Exports<'next-redux-wrapper/out/_next/static/commons/manifest'>;
}
declare module 'next-redux-wrapper/src/index.js' {
  declare module.exports: $Exports<'next-redux-wrapper/src/index'>;
}
declare module 'next-redux-wrapper/src/index.spec.js' {
  declare module.exports: $Exports<'next-redux-wrapper/src/index.spec'>;
}
declare module 'next-redux-wrapper/tests/index.test.js' {
  declare module.exports: $Exports<'next-redux-wrapper/tests/index.test'>;
}
