// flow-typed signature: aa2d438dc048118b7842fb59c23c31b8
// flow-typed version: <<STUB>>/sort-package-json_v^1.16.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sort-package-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sort-package-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sort-package-json/index' {
  declare module.exports: $Exports<'sort-package-json'>;
}
declare module 'sort-package-json/index.js' {
  declare module.exports: $Exports<'sort-package-json'>;
}
