// flow-typed signature: e1488664f06538499d2291dd65b09bce
// flow-typed version: <<STUB>>/@firebase/app-types_v^0.3.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@firebase/app-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@firebase/app-types' {
  declare module.exports: any;
}
